exclude: '(^|/)(__pycache__/|venv/)'

repos:
-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    -   id: black
        name: black
        entry: black
        args: ["--line-length", "120", "--target-version", "py312"]
-   repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
    -   id: isort
        name: isort
        entry: isort
        args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
    -   id: mypy
        name: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
