"""rename filename to path_to_file

Revision ID: 113bc73a19a3
Revises: 1c2952154987
Create Date: 2026-08-18 12:15:21.740837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113bc73a19a3'
down_revision: Union[str, Sequence[str], None] = '1c2952154987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fm_import', 'filename', new_column_name='path_to_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fm_import', 'path_to_file', new_column_name='filename')
    # ### end Alembic commands ###
