"""initial

Revision ID: 1c2952154987
Revises:
Create Date: 2026-08-17 14:25:27.923615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c2952154987"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "save",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fm_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "upload_status",
            sa.Enum("STARTED", "IN_PROGRESS", "FAILED", "COMPLETED", name="importuploadstatus"),
            nullable=False,
        ),
        sa.Column("import_type", sa.Enum("SQUAD", "SHORTLIST", name="importtype"), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("save_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["save_id"],
            ["save.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("save_id", "version", "import_type", name="uq_import_save_version_import_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fm_import")
    op.drop_table("save")
    # ### end Alembic commands ###
